# Site
title:              UWPX
bio:                'A secure XMPP client app for all your UWP (Windows 10) devices.'
description:        "A secure XMPP client app for all your UWP (Windows 10) devices."
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "uwpx.github.io" # the base hostname & protocol for your site
mail: "support@uwpx.org"
xmpp: "com8@xmpp.uwpx.org"
coppyright: "2018 Fabian Sauter"

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
github:             UWPX/UWPX-Client

# personal          
email:              support@uwpx.org

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
